name: Sanitize Artifact Name
description: Replaces all slashes in the branch name with underscores.

inputs:
    name:
        required: true
        description: 'Name to be sanitized'
outputs:
    sanitized_name:
        description: 'Sanitized name'
        value: ${{ steps.sanitize.outputs.sanitized_name }}

runs:
    using: "composite"
    steps:
      - name: Sanitize Artifact Name
        id: sanitize
        run: echo sanitized_name=$(echo ${{ inputs.name }} | sed 's/\//_/g') >> $GITHUB_OUTPUT
        shell: bash