name: Frontend CD (dev env)

# 触发workflow的条件
on:
    workflow_call:

jobs:
    deploy: 
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        
        steps:
            - name: Checkout code
              uses: actions/checkout@master
              with:
                  ref: ${{ github.ref }}

            - id: sanitize_artifact_name
              uses: ./.github/actions/sanitize-name
              with:
                name: ${{ github.ref_name }}
            
            # 下载Flutter构建产物
            - name: 'Download Build Artifacts - ${{ github.ref_name }} - Flutter'
              uses: actions/download-artifact@v3
              with:
                  name: ${{ steps.sanitize_artifact_name.outputs.sanitized_name }}-build-flutter
                  path: flutter/build/web/
            
            # 下载Vue构建产物
            - name: 'Download Build Artifacts - ${{ github.ref_name }} Vue'
              uses: actions/download-artifact@v3
              with:
                  name: ${{ steps.sanitize_artifact_name.outputs.sanitized_name }}-build-vue
                  path: vue/dist/
            
            # 部署到测试服务器
            - name: Incremental Deploy
              uses: easingthemes/ssh-deploy@main
              with:
                SSH_PRIVATE_KEY: ${{ secrets.TEST_SERVER_PRIVATE_KEY }}
                REMOTE_HOST: ${{ secrets.TEST_SERVER_HOST }}
                REMOTE_PORT: ${{ secrets.TEST_SERVER_PORT }}
                REMOTE_USER: ${{ secrets.TEST_SERVER_USERNAME }}
                ARGS: '-avz --delete'
                # https://ss64.com/bash/rsync_options.html
                SOURCE: './'
                TARGET: '/root/redstone_daily/frontend/' # 服务器目标路径

    # 刷新CDN
    # refresh-cdn:
    #     needs: deploy
    #     uses: ./.github/workflows/cd-refresh-cdn.yml