name: frontend cd release
# 触发workflow的条件
on:
    push:
        # 只有main分支发生push事件时，才会触发workflow
        branches: [main]
    pull_request:
        branches: [main]

#env:
#    SERVER_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }} # 服务器私钥
#    SERVER_HOST: ${{ secrets.SERVER_HOST }} # 服务器IP地址
#    USER_NAME: ${{ secrets.USER_NAME }} # 服务器用户名

# jobs表示执行的一项或多项任务
jobs:
    build: # 任务的job_id，具体名称自定义，这里build代表打包
        runs-on: ubuntu-latest # runs-on字段指定运行所需要的虚拟机环境。注意：这个是必填字段
        steps:
            - uses: actions/checkout@master
              with:
                  ref: main

            - name: Print Texts
              run: cat < cyber_budhha.txt && cat < RD_text.txt

            - name: Flutter action
              # You may pin to the exact commit or the version.
              # uses: subosito/flutter-action@1c5eb12d812966ca84680edc38353a0851c8fd56
              uses: subosito/flutter-action@v2
              with:
                  # The Flutter version to make available on the path
                  # flutter-version: '3.19.5'
                  # The Flutter build release channel
                  channel: 'stable'
                  # Cache the Flutter SDK
                  cache: true
                  # Identifier for the Flutter SDK cache
                  # cache-key: # optional, default is flutter-:os:-:channel:-:version:-:arch:-:hash:
                  # Identifier for the Dart .pub-cache cache
                  # pub-cache-key: # optional, default is flutter-pub:os:-:channel:-:version:-:arch:-:hash:
                  # Flutter SDK cache path
                  # cache-path: # optional, default is ${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:
                  # Flutter pub cache path
                  # pub-cache-path: # optional, default is default
                  # The architecture of Flutter SDK executable (x64 or arm64)
                  # architecture: # optional, default is ${{ runner.arch }}
            - run: flutter pub get
            # - run: flutter test
#            - run: flutter build web --web-renderer html --base-href '/daily/' -t ./lib/contentPage/main.dart
            - run: flutter build web --web-renderer canvaskit

            # 上传打包资源
            - name: Deploy
              uses: easingthemes/ssh-deploy@main
              with:
                  SSH_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
                  REMOTE_HOST: ${{ secrets.SERVER_HOST }}
                  REMOTE_PORT: ${{ secrets.SERVER_PORT }}
                  REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
                  ARGS: '-avz --delete'
                  # https://ss64.com/bash/rsync_options.html
                  SOURCE: 'build/web/'
                  TARGET: '/root/redstone_daily/frontend/' # 服务器目标路径
