name: Frontend CD - CDN upload

# 触发workflow的条件
on:
  workflow_call:
    inputs:
      cospath:
        type: string
        required: true
    secrets:
      COS_API_ID:
        required: true
      COS_API_KEY:
        required: true
      COS_API_BUCKET:
        required: true

jobs:
  upload-cdn:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - id: sanitize_artifact_name
        uses: ./.github/actions/sanitize-name
        with:
          name: ${{ github.ref_name }}

      # 下载Flutter构建产物
      - name: 'Download Build Artifacts - ${{ github.ref_name }} - Flutter'
        uses: actions/download-artifact@v3
        with:
          name: ${{ steps.sanitize_artifact_name.outputs.sanitized_name }}-build-flutter
          path: dist/flutter-project/

      # 下载Vue构建产物
      - name: 'Download Build Artifacts - ${{ github.ref_name }} Vue'
        uses: actions/download-artifact@v3
        with:
          name: ${{ steps.sanitize_artifact_name.outputs.sanitized_name }}-build-vue
          path: dist/vue/

      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: 3.10
          # Used to specify the path to dependency files. Supports wildcards or a list of file names for caching multiple dependencies.
          # cache-dependency-path: # optional
          # update-environment: false

      # coscmd
      - name: coscmd
        run: |
          pip install coscmd
          pip install coscmd -U
          coscmd config -a ${{ secrets.COS_API_ID }} -s ${{ secrets.COS_API_KEY }} -b ${{ secrets.COS_API_BUCKET }} -r ap-hongkong
          coscmd upload -rfs --delete ./dist ${{ inputs.cospath }} --ignore ".DS_Store" --ignore ".git*"