name: Build Vue Project

# 触发workflow的条件
on:
    workflow_call:
        inputs:
            dir:
                required: true
                type: string
                description: 'Vue Project Directory'

jobs:
    # 构建Vue项目任务
    build-vue:
        runs-on: ubuntu-latest # runs-on字段指定运行所需要的虚拟机环境。注意：这个是必填字段
        
        defaults:
            run:
                shell: bash
                working-directory: ${{ inputs.dir }}

        steps:
            - name: Checkout code
              uses: actions/checkout@master
              with:
                  ref: ${{ github.ref }}

            # Todo...
                  
            - name: 'Upload Build Artifacts (name: flutter-web-build)'
              uses: actions/upload-artifact@v3
              with:
                  name: ${{ github.ref }}-build-vue
                  path: ${{ inputs.dir }}- # ?????????