name: Build Vue Project

# 触发workflow的条件
on:
    workflow_call:
        inputs:
            dir:
                required: true
                type: string
                description: 'Vue Project Directory'

jobs:
    # 构建Vue项目任务
    build-vue:
        runs-on: ubuntu-latest # runs-on字段指定运行所需要的虚拟机环境。注意：这个是必填字段
        
        defaults:
            run:
                shell: bash
                working-directory: ${{ inputs.dir }}

        steps:
            - name: Checkout code
              uses: actions/checkout@master
              with:
                  ref: ${{ github.ref }}

            # Todo...

            - id: sanitize_artifact_name
              uses: ./.github/workflows/util-sanitize-name.yml
              with:
                name: ${{ github.ref_name }}
                  
            - name: 'Upload Build Artifacts - ${{ github.ref_name }} - Vue'
              if: steps.sanitize_artifact_name.outputs.sanitized_name
              uses: actions/upload-artifact@v3
              with:
                name: ${{ steps.sanitize_artifact_name.outputs.sanitized_name }}-build-flutter
                path: ${{ inputs.dir }}/dist 	# 是这个没错吧？