name: CI

# 备注：
# 坑！！！！！巨坑！！！！！！！
# shell会使用我们预定的工作目录，但各job的路径参数并不会使用预定工作目录！！！

# TODO:
# cache源码 检测子模块变动->选择性构建
# cache产物&编译缓存 -> 增量编译

# 触发workflow的条件
on:
    workflow_call:

jobs:
    # 进行一些施法（
    spellcasting:
        runs-on: ubuntu-latest # runs-on字段指定运行所需要的虚拟机环境。注意：这个是必填字段
        
        defaults:
            run:
                shell: bash

        steps:
            - name: Checkout code
              uses: actions/checkout@master
              with:
                ref: ${{ github.ref }}

            - name: Print Texts
              run: cat < .github/cyber_budhha.txt && cat < .github/RD_text.txt

    # # 构建flutter项目
    # build-flutter:
    #     needs: spellcasting
    #     uses: ./.github/workflows/ci-build-flutter.yml
    #     with:
    #         dir: ./flutter_project

    # 构建vue项目
    build-vue:
        needs: spellcasting
        uses: ./.github/workflows/ci-build-vue.yml
        with:
            dir: ./vue  